//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.API.scr.Shared.Resource.ApiResponse {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal messages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Parking.API.scr.Shared.Resource.ApiResponse.messages", typeof(messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El token de acceso es inválido..
        /// </summary>
        public static string AccessTokenInvalid {
            get {
                return ResourceManager.GetString("AccessTokenInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cuenta de usuario ya fue verificada..
        /// </summary>
        public static string AccountAlreadyVerified {
            get {
                return ResourceManager.GetString("AccountAlreadyVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pueden editar los datos de un SuperAdministrador..
        /// </summary>
        public static string CannotEditSuperadmin {
            get {
                return ResourceManager.GetString("CannotEditSuperadmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puede editar su propio perfil..
        /// </summary>
        public static string CannotEditYourOwnProfile {
            get {
                return ResourceManager.GetString("CannotEditYourOwnProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede eliminar a un SuperAdministrador..
        /// </summary>
        public static string CannotRemoveSuperadmin {
            get {
                return ResourceManager.GetString("CannotRemoveSuperadmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puede eliminar su propio perfil..
        /// </summary>
        public static string CannotRemoveYourOwnProfile {
            get {
                return ResourceManager.GetString("CannotRemoveYourOwnProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puede actualizar un recurso de otro usuario..
        /// </summary>
        public static string CannotUpdateAnotherUserResource {
            get {
                return ResourceManager.GetString("CannotUpdateAnotherUserResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo enviar el correo electrónico..
        /// </summary>
        public static string CouldNotSendEmail {
            get {
                return ResourceManager.GetString("CouldNotSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cuenta de usuario se creó con éxito. Confirme su correo electrónico..
        /// </summary>
        public static string CreateBasicUserAccount {
            get {
                return ResourceManager.GetString("CreateBasicUserAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cuenta fue creada con éxito..
        /// </summary>
        public static string CreateEmployeeAccount {
            get {
                return ResourceManager.GetString("CreateEmployeeAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El recurso se creó con éxito..
        /// </summary>
        public static string CreateResource {
            get {
                return ResourceManager.GetString("CreateResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El recurso se eliminó con éxito..
        /// </summary>
        public static string DeleteResource {
            get {
                return ResourceManager.GetString("DeleteResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El documento de identidad está vacío..
        /// </summary>
        public static string DocumentIsEmpty {
            get {
                return ResourceManager.GetString("DocumentIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El documento de identidad es inválido..
        /// </summary>
        public static string DocumentIsInvalid {
            get {
                return ResourceManager.GetString("DocumentIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El documento de identidad debe tener {0} caracteres..
        /// </summary>
        public static string DocumentMaxCharacters {
            get {
                return ResourceManager.GetString("DocumentMaxCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El documento de identidad debe ser numérico..
        /// </summary>
        public static string DocumentMustBeNumeric {
            get {
                return ResourceManager.GetString("DocumentMustBeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo electrónico no está confirmado..
        /// </summary>
        public static string EmailNotConfirmed {
            get {
                return ResourceManager.GetString("EmailNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo electrónico o la contraseña son incorrectos..
        /// </summary>
        public static string EmailOrPasswordIncorrect {
            get {
                return ResourceManager.GetString("EmailOrPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico verificado con éxito..
        /// </summary>
        public static string EmailSuccessfullyVerified {
            get {
                return ResourceManager.GetString("EmailSuccessfullyVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El token de verificación de correo es inválido..
        /// </summary>
        public static string EmailVerificationTokenInvalid {
            get {
                return ResourceManager.GetString("EmailVerificationTokenInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recurso obtenido con éxito..
        /// </summary>
        public static string GetResource {
            get {
                return ResourceManager.GetString("GetResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tiene un refresh token para revocar..
        /// </summary>
        public static string HasNoRefreshToken {
            get {
                return ResourceManager.GetString("HasNoRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta de usuario inactiva..
        /// </summary>
        public static string InactiveUserAccount {
            get {
                return ResourceManager.GetString("InactiveUserAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se produjeron errores de validación..
        /// </summary>
        public static string InvalidModelState {
            get {
                return ResourceManager.GetString("InvalidModelState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Claim faltante en el token: {0}.
        /// </summary>
        public static string MissingClaim {
            get {
                return ResourceManager.GetString("MissingClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña actual es incorrecta..
        /// </summary>
        public static string OldPasswordIncorrect {
            get {
                return ResourceManager.GetString("OldPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe tener al menos una letra minúscula..
        /// </summary>
        public static string PasswordHasNotLowerCaseLetters {
            get {
                return ResourceManager.GetString("PasswordHasNotLowerCaseLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe tener al menos un número..
        /// </summary>
        public static string PasswordHasNotNumbers {
            get {
                return ResourceManager.GetString("PasswordHasNotNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe tener al menos una letra mayúscula..
        /// </summary>
        public static string PasswordHasNotUpperCaseLetters {
            get {
                return ResourceManager.GetString("PasswordHasNotUpperCaseLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña no puede estar vacía..
        /// </summary>
        public static string PasswordIsEmpty {
            get {
                return ResourceManager.GetString("PasswordIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe tener al menos 5 caracteres..
        /// </summary>
        public static string PasswordMinimumCharacters {
            get {
                return ResourceManager.GetString("PasswordMinimumCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El token de restablecimiento de contraseña es inválido..
        /// </summary>
        public static string PasswordResetTokenInvalid {
            get {
                return ResourceManager.GetString("PasswordResetTokenInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña se restableció con éxito..
        /// </summary>
        public static string PasswordSuccessfullyReset {
            get {
                return ResourceManager.GetString("PasswordSuccessfullyReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tiene permisos para realizar esta acción..
        /// </summary>
        public static string PermitsNotGranted {
            get {
                return ResourceManager.GetString("PermitsNotGranted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se detectó una violación de restricción de referencia en la base de datos..
        /// </summary>
        public static string ReferenceConstraintViolated {
            get {
                return ResourceManager.GetString("ReferenceConstraintViolated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El refresh token ha expirado..
        /// </summary>
        public static string RefreshTokenExpired {
            get {
                return ResourceManager.GetString("RefreshTokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El refresh token es inválido..
        /// </summary>
        public static string RefreshTokenInvalid {
            get {
                return ResourceManager.GetString("RefreshTokenInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El recurso pertenece a otro usuario..
        /// </summary>
        public static string ResourceFromAnotherUser {
            get {
                return ResourceManager.GetString("ResourceFromAnotherUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recurso no encontrado..
        /// </summary>
        public static string ResourceNotFound {
            get {
                return ResourceManager.GetString("ResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El refresh token fue revocado correctamente..
        /// </summary>
        public static string RevokeToken {
            get {
                return ResourceManager.GetString("RevokeToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se envió el correo para restablecer la contraseña..
        /// </summary>
        public static string SendPasswordResetLink {
            get {
                return ResourceManager.GetString("SendPasswordResetLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio de sesión exitoso..
        /// </summary>
        public static string SuccessfulLogin {
            get {
                return ResourceManager.GetString("SuccessfulLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La session se ah creado correctamente.
        /// </summary>
        public static string SuccessfulParkingSessionCreate {
            get {
                return ResourceManager.GetString("SuccessfulParkingSessionCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se produjo un error inesperado. Intente nuevamente..
        /// </summary>
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se encontraron errores inesperados. Intente nuevamente..
        /// </summary>
        public static string UnexpectedErrors {
            get {
                return ResourceManager.GetString("UnexpectedErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se detectó una violación de restricción única en la base de datos..
        /// </summary>
        public static string UniqueConstraintViolated {
            get {
                return ResourceManager.GetString("UniqueConstraintViolated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El archivo no puede ser reconocido por el sistema..
        /// </summary>
        public static string UnrecognizableFile {
            get {
                return ResourceManager.GetString("UnrecognizableFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El access token se actualizó correctamente..
        /// </summary>
        public static string UpdatedAccessToken {
            get {
                return ResourceManager.GetString("UpdatedAccessToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El recurso se actualizó con éxito..
        /// </summary>
        public static string UpdateResource {
            get {
                return ResourceManager.GetString("UpdateResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo electrónico ya está en uso por otro usuario..
        /// </summary>
        public static string UsernameAlreadyExists {
            get {
                return ResourceManager.GetString("UsernameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario no encontrado..
        /// </summary>
        public static string UsernameNotFound {
            get {
                return ResourceManager.GetString("UsernameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La placa del vehiculo ya esta siendo utilazada .
        /// </summary>
        public static string VehicleAlreadyExists {
            get {
                return ResourceManager.GetString("VehicleAlreadyExists", resourceCulture);
            }
        }
    }
}
